"""Stage 08 — the infographic engine (§13).

Cards are rendered by us, never generated by a model. Generative models lie in
numbers and labels, and a wrong figure on screen is the one mistake this channel
cannot make (§11.2). So: verified claims in, HTML+CSS out, a browser screenshot
or a WebM with alpha back.

Seven templates, all from the references the client picked (§1.4):

    BIG_NUMBER      one huge figure, counter animation
    BAR_RANK        ranked rows with growing bars      (Brand Analytics look)
    COMPARISON_AB   before/after either side of a rule
    TIMELINE        years on an axis, active point lit
    ICON_FACT_LIST  round icons plus short facts       (YouTube-stats look)
    PROCESS_ARROW   anchor → arrow → verb → anchor     ("X hacked Y")
    SCREEN_CARD     an article card in brand style

PROCESS_ARROW is the one the client described by hand: a ChatGPT icon, an arrow,
Hugging Face, and a breach. Its beat timing (§13.2 T6) is baked in so the card
drops straight into the 1.2-2.2s rhythm instead of fighting it.
"""

from __future__ import annotations

import html
import json
import os
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..core.config import Config
from ..core.log import get_logger
from ..core.schemas import InfographicSpec
from .icons import IconBank

log = get_logger("s08")

STAGE = "s08_infographic"

WIDTH, HEIGHT = 1080, 1920

#: §13.2 T6 — anchor 0.35 → arrow 0.40 → verb 0.20 → anchor 0.35 → result 0.40.
PROCESS_BEATS = {"anchor_a": 0.35, "arrow": 0.40, "verb": 0.20, "anchor_b": 0.35, "result": 0.40}

#: §13.3 — a card that lives under this is not readable at all.
MIN_CARD_S = 1.6
MAX_CARD_S = 3.4


@dataclass
class BrandTokens:
    """Everything a template needs from config/brand.yaml, resolved once."""

    bg: str
    bg_secondary: str
    accent: str
    accent_hot: str
    text: str
    muted: str
    gold: str
    font_head: str
    font_body: str
    font_num: str
    glow_text: str
    glow_soft: str
    radius: int
    grid: int

    @classmethod
    def from_config(cls, config: Config) -> BrandTokens:
        return cls(
            bg=config.brand("colors.bg_primary"),
            bg_secondary=config.brand("colors.bg_secondary"),
            accent=config.brand("colors.accent"),
            accent_hot=config.brand("colors.accent_hot"),
            text=config.brand("colors.text"),
            muted=config.brand("colors.muted"),
            gold=config.brand("colors.gold"),
            font_head=config.brand("fonts.head"),
            font_body=config.brand("fonts.body"),
            font_num=config.brand("fonts.num"),
            glow_text=config.brand("effects.glow_text"),
            glow_soft=config.brand("effects.glow_soft"),
            radius=int(config.brand("effects.radius_px")),
            grid=int(config.brand("effects.grid_unit_px")),
        )


@dataclass
class RenderedCard:
    spec: InfographicSpec
    html_path: Path
    image_path: Path | None = None
    duration_s: float = 2.4
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.image_path is not None and self.image_path.exists()


# --------------------------------------------------------------------------- #
# Template selection
# --------------------------------------------------------------------------- #


def choose_template(beat_text: str, items: list[dict[str, Any]]) -> str:
    """Pick a template from the shape of the fact, not from taste.

    §22.8 is explicit about one case: anything of the form "X did something to
    Y" is always PROCESS_ARROW. That is the client's own example and the most
    common shape in AI/IT news.
    """
    lowered = beat_text.lower()
    if any(verb in lowered for verb in _ACTION_VERBS):
        return "PROCESS_ARROW"
    if len(items) >= 3 and all(item.get("value") for item in items):
        return "BAR_RANK"
    if len(items) == 2:
        return "COMPARISON_AB"
    if len(items) == 1:
        return "BIG_NUMBER"
    if any(str(item.get("label", "")).strip().isdigit() for item in items):
        return "TIMELINE"
    return "ICON_FACT_LIST"


_ACTION_VERBS = (
    "взлом",
    "обош",
    "превзош",
    "обогн",
    "поглот",
    "купил",
    "запуст",
    "атаков",
    "подмен",
    "украл",
    "слил",
    "hack",
    "breach",
    "beat",
    "overtook",
    "acquired",
)


def card_duration(template: str, items: list[Any], requested: float = 0.0) -> float:
    """Clamp a card into the window where it is both readable and rhythmic."""
    # PROCESS_ARROW has its own beat sheet; everything else gets a second of
    # reading time per unit, plus the entrance.
    natural = sum(PROCESS_BEATS.values()) if template == "PROCESS_ARROW" else 1.0 + 0.55 * max(1, len(items))
    return round(max(MIN_CARD_S, min(requested or natural, MAX_CARD_S)), 3)


# --------------------------------------------------------------------------- #
# HTML
# --------------------------------------------------------------------------- #


def build_html(spec: InfographicSpec, tokens: BrandTokens, icons: IconBank | None = None) -> str:
    """Render one card to a standalone HTML document.

    With an `IconBank`, company and app marks are resolved to inline data URIs
    before the template runs, so the templates themselves stay unaware of where
    an icon came from — a resolved mark and a drawn glyph reach them the same
    way.
    """
    body = _TEMPLATES[spec.template](_with_icons(spec, icons), tokens)
    return _PAGE.format(
        title=html.escape(spec.title or spec.template),
        width=WIDTH,
        height=HEIGHT,
        css=_base_css(tokens),
        body=body,
    )


def _with_icons(spec: InfographicSpec, icons: IconBank | None) -> InfographicSpec:
    """Swap icon keywords for real marks where the bank has one."""
    if icons is None or not spec.items:
        return spec
    resolved = spec.model_copy(deep=True)
    for item in resolved.items:
        # An explicit keyword wins as the lookup term; the label is the
        # fallback because "OpenAI" is what a card actually names.
        uri = icons.resolve(item.icon or item.label)
        if uri:
            item.icon = uri
    return resolved


def _big_number(spec: InfographicSpec, tokens: BrandTokens) -> str:
    item = spec.items[0] if spec.items else None
    value = html.escape(item.value if item else "")
    label = html.escape(item.label if item else "")
    return f"""
<div class="card center">
  <div class="eyebrow">{html.escape(spec.title)}</div>
  <div class="bignum" data-count="{value}">{value}</div>
  <div class="biglabel">{label}</div>
  {_source(spec)}
</div>"""


def _bar_rank(spec: InfographicSpec, tokens: BrandTokens) -> str:
    """Direct descendant of the Brand Analytics reference (§1.4)."""
    peak = _peak(spec)
    rows = []
    for index, item in enumerate(spec.items):
        share = (_numeric(item.value) / peak * 100) if peak else 0
        rows.append(
            f"""
  <div class="row" style="--delay:{index * 0.06:.2f}s">
    <div class="rowhead">
      <span class="rowlabel">{html.escape(item.label)}</span>
      <span class="rowvalue">{html.escape(item.value)}</span>
    </div>
    <div class="bartrack"><div class="bar" style="--w:{share:.1f}%"></div></div>
  </div>"""
        )
    return f"""
<div class="card">
  <div class="cardtitle">{html.escape(spec.title)}</div>
  <div class="rows">{"".join(rows)}</div>
  {_source(spec)}
</div>"""


def _comparison(spec: InfographicSpec, tokens: BrandTokens) -> str:
    left = spec.items[0] if spec.items else None
    right = spec.items[1] if len(spec.items) > 1 else None
    return f"""
<div class="card">
  <div class="cardtitle">{html.escape(spec.title)}</div>
  <div class="ab">
    <div class="abside" style="--delay:0s">
      {_icon_capsule(left.icon if left else "")}
      <div class="abvalue">{html.escape(left.value if left else "")}</div>
      <div class="ablabel">{html.escape(left.label if left else "")}</div>
    </div>
    <div class="abrule"></div>
    <div class="abside" style="--delay:.25s">
      {_icon_capsule(right.icon if right else "")}
      <div class="abvalue hot">{html.escape(right.value if right else "")}</div>
      <div class="ablabel">{html.escape(right.label if right else "")}</div>
    </div>
  </div>
  {_source(spec)}
</div>"""


def _timeline(spec: InfographicSpec, tokens: BrandTokens) -> str:
    points = []
    for index, item in enumerate(spec.items):
        active = " active" if item.note == "active" else ""
        points.append(
            f"""
    <div class="tlpoint{active}" style="--delay:{0.2 + index * 0.12:.2f}s">
      <div class="tldot"></div>
      <div class="tlyear">{html.escape(item.value or item.label)}</div>
      <div class="tlnote">{html.escape(item.label if item.value else "")}</div>
    </div>"""
        )
    return f"""
<div class="card">
  <div class="cardtitle">{html.escape(spec.title)}</div>
  <div class="tl"><div class="tlaxis"></div>{"".join(points)}</div>
  {_source(spec)}
</div>"""


def _icon_fact_list(spec: InfographicSpec, tokens: BrandTokens) -> str:
    rows = []
    for index, item in enumerate(spec.items[:5]):
        rows.append(
            f"""
  <div class="fact" style="--delay:{index * 0.09:.2f}s">
    {_icon_capsule(item.icon, size=72)}
    <div class="facttext">
      <span class="factvalue">{html.escape(item.value)}</span>
      <span class="factlabel">{html.escape(item.label)}</span>
    </div>
  </div>"""
        )
    return f"""
<div class="card">
  <div class="cardtitle">{html.escape(spec.title)}</div>
  <div class="facts">{"".join(rows)}</div>
  {_source(spec)}
</div>"""


def _process_arrow(spec: InfographicSpec, tokens: BrandTokens) -> str:
    """The client's own case: icon → hand-drawn arrow → verb → icon → breach.

    The arrow is a quadratic Bezier with a deliberate wobble: a perfectly
    straight arrow reads as PowerPoint, and this channel is not PowerPoint.
    """
    anchor_a = spec.items[0] if spec.items else None
    anchor_b = spec.items[1] if len(spec.items) > 1 else None
    result = spec.items[2] if len(spec.items) > 2 else None
    verb = spec.accent_word or "→"

    result_block = ""
    if result:
        result_block = f"""
  <div class="result" style="--delay:1.30s">
    {_icon_capsule(result.icon or "alert", size=140, danger=True)}
    <div class="resultlabel">{html.escape(result.label or result.value)}</div>
  </div>"""

    return f"""
<div class="card process">
  <div class="cardtitle">{html.escape(spec.title)}</div>
  <div class="chain">
    <div class="anchor" style="--delay:0s">
      {_icon_capsule(anchor_a.icon if anchor_a else "", size=180)}
      <div class="anchorlabel">{html.escape(anchor_a.label if anchor_a else "")}</div>
    </div>

    <div class="arrowbox">
      <svg viewBox="0 0 420 160" class="arrow" preserveAspectRatio="none">
        <defs>
          <marker id="head" markerWidth="9" markerHeight="9" refX="6" refY="4.5" orient="auto">
            <path d="M0,0 L9,4.5 L0,9 z" fill="{tokens.accent}"/>
          </marker>
        </defs>
        <path d="M 10,96 Q 200,34 400,88" fill="none" stroke="{tokens.accent}"
              stroke-width="6" stroke-linecap="round" marker-end="url(#head)"/>
      </svg>
      <div class="verb" style="--delay:0.75s">{html.escape(verb)}</div>
    </div>

    <div class="anchor" style="--delay:0.95s">
      {_icon_capsule(anchor_b.icon if anchor_b else "", size=180)}
      <div class="anchorlabel">{html.escape(anchor_b.label if anchor_b else "")}</div>
    </div>
  </div>
  {result_block}
  {_source(spec)}
</div>"""


def _screen_card(spec: InfographicSpec, tokens: BrandTokens) -> str:
    lead = spec.items[0].label if spec.items else ""
    date = spec.items[0].value if spec.items else ""
    return f"""
<div class="card">
  <div class="screencard">
    <div class="screenrule"></div>
    <div class="screenbody">
      <div class="screendomain">{html.escape(spec.source)}</div>
      <div class="screenhead">{_highlight(spec.title, spec.accent_word)}</div>
      <div class="screendate">{html.escape(date)}</div>
      <div class="screenlead">{html.escape(lead)}</div>
    </div>
  </div>
</div>"""


_TEMPLATES = {
    "BIG_NUMBER": _big_number,
    "BAR_RANK": _bar_rank,
    "COMPARISON_AB": _comparison,
    "TIMELINE": _timeline,
    "ICON_FACT_LIST": _icon_fact_list,
    "PROCESS_ARROW": _process_arrow,
    "SCREEN_CARD": _screen_card,
}


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #


def render_card(
    spec: InfographicSpec,
    config: Config,
    destination: Path,
    *,
    transparent: bool = True,
    icons: IconBank | None = None,
) -> RenderedCard:
    """HTML → PNG via headless Chromium. Falls back to HTML only if it is absent."""
    tokens = BrandTokens.from_config(config)
    destination.mkdir(parents=True, exist_ok=True)

    html_path = destination / f"{spec.shot_id}.html"
    html_path.write_text(build_html(spec, tokens, icons), encoding="utf-8")

    card = RenderedCard(
        spec=spec,
        html_path=html_path,
        duration_s=card_duration(spec.template, spec.items, spec.duration_s),
    )
    image_path = destination / f"{spec.shot_id}.png"
    if _screenshot(html_path, image_path, transparent=transparent):
        card.image_path = image_path
        log.info(
            "%s: %s card rendered (%.2fs on screen)",
            spec.shot_id,
            spec.template,
            card.duration_s,
            extra={"stage": STAGE},
        )
    else:
        card.warnings.append("no headless browser; the card exists as HTML only")
    return card


def _screenshot(html_path: Path, image_path: Path, *, transparent: bool) -> bool:
    """Shoot the card with Playwright's Chromium if it is installed."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log.info("playwright not installed; skipping card screenshot", extra={"stage": STAGE})
        return False

    try:
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(
                executable_path=_chromium_path(),
                args=["--force-color-profile=srgb", "--no-sandbox"],
            )
            page = browser.new_page(
                viewport={"width": WIDTH, "height": HEIGHT},
                device_scale_factor=1,
            )
            page.goto(html_path.resolve().as_uri())
            # Drive the clock to the end instead of sleeping: entrance delays
            # run past 1.3s, and a fixed wait silently cropped late elements.
            page.evaluate(_FINISH_ANIMATIONS)
            page.wait_for_timeout(60)
            page.screenshot(path=str(image_path), omit_background=transparent)
            browser.close()
    except Exception as exc:  # a browser failure must not kill the run
        log.warning("card screenshot failed: %s", exc, extra={"stage": STAGE})
        return False
    return image_path.exists()


def _chromium_path() -> str | None:
    """Find a browser the image already ships.

    The runner pins its own Chromium under PLAYWRIGHT_BROWSERS_PATH, and the
    build must never download one: an offline Actions runner would hang there.
    Returning None lets Playwright use its own default when nothing is pinned.
    """
    override = os.environ.get("REDSHIFT_CHROMIUM")
    if override and Path(override).exists():
        return override
    root = Path(os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers"))
    for pattern in (
        "chromium-*/chrome-linux/chrome",
        "chromium_headless_shell-*/chrome-linux/headless_shell",
    ):
        for candidate in sorted(root.glob(pattern), reverse=True):
            if candidate.is_file():
                return str(candidate)
    for name in ("chromium", "chromium-browser", "google-chrome"):
        found = shutil.which(name)
        if found:
            return found
    return None


def render_animation(
    card: RenderedCard,
    destination: Path,
    *,
    fps: int = 30,
    ffmpeg: str = "ffmpeg",
) -> Path | None:
    """Render the card as a real animation: WebM with alpha.

    Frames come from stepping the browser's animation clock, not from panning a
    still — the arrow has to actually draw itself and the bars have to actually
    grow. That is the difference between a slide and a shot.
    """
    if not shutil.which(ffmpeg):
        return None
    frames_dir = destination / f"{card.spec.shot_id}_frames"
    frames = _render_frames(card.html_path, frames_dir, card.duration_s, fps)
    if not frames:
        return None

    target = destination / f"{card.spec.shot_id}.webm"
    command = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-y",
        "-framerate", str(fps), "-i", str(frames_dir / "f_%04d.png"),
        "-c:v", "libvpx-vp9", "-pix_fmt", "yuva420p", "-b:v", "4M", "-auto-alt-ref", "0",
        str(target),
    ]  # fmt: skip
    result = subprocess.run(command, capture_output=True, timeout=600, check=False)
    shutil.rmtree(frames_dir, ignore_errors=True)
    if result.returncode != 0 or not target.exists():
        log.warning(
            "card animation failed: %s",
            result.stderr.decode("utf-8", "replace")[:200],
            extra={"stage": STAGE},
        )
        return None
    log.info("%s: animated %.2fs at %dfps", card.spec.shot_id, card.duration_s, fps, extra={"stage": STAGE})
    return target


def _render_frames(html_path: Path, frames_dir: Path, duration: float, fps: int) -> list[Path]:
    """Shoot one PNG per frame with the animation clock pinned to that instant."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return []

    frames_dir.mkdir(parents=True, exist_ok=True)
    count = max(2, int(round(duration * fps)))
    written: list[Path] = []
    try:
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(
                executable_path=_chromium_path(),
                args=["--force-color-profile=srgb", "--no-sandbox"],
            )
            page = browser.new_page(viewport={"width": WIDTH, "height": HEIGHT}, device_scale_factor=1)
            page.goto(html_path.resolve().as_uri())
            page.evaluate(_PAUSE_ANIMATIONS)
            for index in range(count):
                page.evaluate(_SEEK_ANIMATIONS, index / fps * 1000.0)
                frame = frames_dir / f"f_{index:04d}.png"
                page.screenshot(path=str(frame), omit_background=True)
                written.append(frame)
            browser.close()
    except Exception as exc:
        log.warning("frame capture failed: %s", exc, extra={"stage": STAGE})
        return []
    return written


#: Pinning the clock makes every frame reproducible; without it the capture
#: races the browser and the same card renders differently each run.
_PAUSE_ANIMATIONS = "() => document.getAnimations().forEach(a => a.pause())"
_SEEK_ANIMATIONS = "t => document.getAnimations().forEach(a => { try { a.currentTime = t; } catch (e) {} })"
_FINISH_ANIMATIONS = """() => document.getAnimations().forEach(a => {
  try { a.finish(); } catch (e) { a.currentTime = 100000; }
})"""


def write_manifest(cards: list[RenderedCard], path: Path) -> Path:
    """`infographics.json` — timings the timeline needs (§13.4)."""
    payload = {
        "schema_version": "1.0",
        "cards": [
            {
                **card.spec.model_dump(),
                "file": str(card.image_path) if card.image_path else "",
                "html": str(card.html_path),
                "duration_s": card.duration_s,
                "warnings": card.warnings,
            }
            for card in cards
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


# --------------------------------------------------------------------------- #
# Fragments
# --------------------------------------------------------------------------- #


def _icon_capsule(icon: str, size: int = 120, *, danger: bool = False) -> str:
    """A logo in a brand capsule (§9.4): circle, faint fill, thin ring.

    `icon` is either a path to a downloaded logo or a keyword; a keyword falls
    back to a drawn glyph so a missing logo never leaves a hole in the card.
    """
    inner = (
        f'<img src="{html.escape(icon)}" alt="">'
        if icon and ("/" in icon or icon.endswith((".png", ".svg", ".jpg", ".webp")))
        else f'<span class="glyph">{_GLYPHS.get(icon, _GLYPHS["default"])}</span>'
    )
    classes = "capsule danger" if danger else "capsule"
    return f'<div class="{classes}" style="--size:{size}px">{inner}</div>'


#: Drawn fallbacks, so a card never waits on a logo download.
_GLYPHS = {
    "alert": "⚠",
    "lock": "🔒",
    "shield": "🛡",
    "ai": "◈",
    "data": "▤",
    "cloud": "☁",
    "rocket": "▲",
    "default": "◆",
}


def _source(spec: InfographicSpec) -> str:
    """§13.3: the source of a figure is always on the card, in small type."""
    if not spec.source:
        return ""
    return f'<div class="source">{html.escape(spec.source)}</div>'


def _highlight(text: str, accent: str) -> str:
    escaped = html.escape(text)
    if accent and accent in text:
        return escaped.replace(html.escape(accent), f"<mark>{html.escape(accent)}</mark>", 1)
    return escaped


def _numeric(value: str) -> float:
    digits = "".join(char for char in str(value) if char.isdigit() or char in ".,")
    try:
        return float(digits.replace(",", "."))
    except ValueError:
        return 0.0


def _peak(spec: InfographicSpec) -> float:
    return max((_numeric(item.value) for item in spec.items), default=0.0)


# --------------------------------------------------------------------------- #
# CSS and page shell
# --------------------------------------------------------------------------- #


def _base_css(t: BrandTokens) -> str:
    return f"""
* {{ margin:0; padding:0; box-sizing:border-box; }}
html, body {{ width:{WIDTH}px; height:{HEIGHT}px; background:transparent; }}
body {{
  font-family:"{t.font_body}", Inter, system-ui, sans-serif;
  color:{t.text};
  display:flex; align-items:center; justify-content:center;
}}
.card {{
  width:{WIDTH - 2 * 96}px;
  padding:{t.grid * 2}px;
  background:linear-gradient(180deg, {t.bg}F2 0%, {t.bg_secondary}F2 100%);
  border:1px solid rgba(241,245,249,.10);
  border-radius:{t.radius * 2}px;
  box-shadow:{t.glow_soft}, 0 40px 120px rgba(0,0,0,.65);
}}
.card.center {{ text-align:center; }}
.cardtitle {{
  font-family:"{t.font_head}", sans-serif; font-weight:700; font-size:44px;
  letter-spacing:-.01em; margin-bottom:{t.grid * 1.5}px;
  animation:rise .45s cubic-bezier(.2,.9,.25,1.1) both;
}}
.eyebrow {{
  font-family:"{t.font_head}", sans-serif; font-size:34px; color:{t.muted};
  text-transform:uppercase; letter-spacing:.08em; margin-bottom:{t.grid}px;
  animation:rise .4s ease-out both;
}}
.source {{
  margin-top:{t.grid * 1.5}px; font-size:22px; color:{t.muted};
  animation:fade .5s ease-out .6s both;
}}

/* T1 BIG_NUMBER */
.bignum {{
  font-family:"{t.font_num}", monospace; font-weight:700; font-size:280px;
  line-height:.95; color:{t.text}; text-shadow:{t.glow_text};
  animation:pop .55s cubic-bezier(.2,.9,.25,1.15) both;
}}
.biglabel {{ font-size:40px; color:{t.muted}; margin-top:{t.grid}px;
  animation:rise .45s ease-out .2s both; }}

/* T2 BAR_RANK */
.rows {{ display:flex; flex-direction:column; gap:{t.grid * 0.7}px; }}
.row {{ background:rgba(241,245,249,.04); border-radius:8px;
  padding:{t.grid * 0.6}px {t.grid}px; animation:rise .4s ease-out var(--delay) both; }}
.rowhead {{ display:flex; justify-content:space-between; align-items:baseline;
  margin-bottom:10px; }}
.rowlabel {{ font-size:34px; }}
.rowvalue {{ font-family:"{t.font_num}", monospace; font-size:34px; color:{t.text}; }}
.bartrack {{ height:16px; background:rgba(241,245,249,.06); border-radius:8px; overflow:hidden; }}
.bar {{ height:100%; width:var(--w); border-radius:8px;
  background:linear-gradient(90deg, {t.accent}, {t.accent_hot});
  animation:grow .7s cubic-bezier(.2,.9,.25,1) var(--delay) both; }}

/* T3 COMPARISON_AB */
.ab {{ display:flex; align-items:center; gap:{t.grid}px; }}
.abside {{ flex:1; text-align:center; animation:rise .5s cubic-bezier(.2,.9,.25,1.1) var(--delay) both; }}
.abrule {{ width:2px; align-self:stretch; background:linear-gradient(180deg,
  transparent, {t.accent}, transparent); }}
.abvalue {{ font-family:"{t.font_num}", monospace; font-size:96px; margin-top:{t.grid}px; }}
.abvalue.hot {{ color:{t.accent_hot}; text-shadow:{t.glow_text}; }}
.ablabel {{ font-size:32px; color:{t.muted}; }}

/* T4 TIMELINE */
.tl {{ position:relative; display:flex; justify-content:space-between;
  padding:{t.grid * 2}px 0; }}
.tlaxis {{ position:absolute; left:0; right:0; top:50%; height:2px;
  background:rgba(241,245,249,.14); animation:draw .6s ease-out both; }}
.tlpoint {{ text-align:center; animation:rise .4s ease-out var(--delay) both; }}
.tldot {{ width:18px; height:18px; border-radius:50%; margin:0 auto 12px;
  background:{t.muted}; }}
.tlpoint.active .tldot {{ width:28px; height:28px; background:{t.accent};
  box-shadow:{t.glow_text}; }}
.tlyear {{ font-family:"{t.font_num}", monospace; font-size:34px; }}
.tlnote {{ font-size:24px; color:{t.muted}; }}

/* T5 ICON_FACT_LIST */
.facts {{ display:flex; flex-direction:column; gap:{t.grid}px; }}
.fact {{ display:flex; align-items:center; gap:{t.grid}px;
  animation:rise .42s ease-out var(--delay) both; }}
.facttext {{ display:flex; flex-direction:column; }}
.factvalue {{ font-family:"{t.font_num}", monospace; font-size:44px; }}
.factlabel {{ font-size:30px; color:{t.muted}; }}

/* T6 PROCESS_ARROW */
.process .chain {{ display:flex; align-items:center; justify-content:space-between;
  gap:{t.grid}px; margin-top:{t.grid}px; }}
.anchor {{ text-align:center; animation:pop .42s cubic-bezier(.2,.9,.25,1.15) var(--delay) both; }}
.anchorlabel {{ font-size:32px; margin-top:14px; }}
.arrowbox {{ position:relative; flex:1; height:170px; }}
.arrow {{ width:100%; height:100%; }}
.arrow path {{ stroke-dasharray:520; stroke-dashoffset:520;
  animation:stroke .40s ease-out .35s both; }}
.verb {{ position:absolute; left:50%; top:6px; transform:translateX(-50%);
  font-family:"{t.font_head}", sans-serif; font-weight:700; font-size:38px;
  color:{t.accent_hot}; text-shadow:{t.glow_text};
  animation:pop .22s cubic-bezier(.2,.9,.25,1.2) var(--delay) both; }}
.result {{ display:flex; align-items:center; justify-content:center; gap:{t.grid}px;
  margin-top:{t.grid * 1.5}px; animation:pop .40s cubic-bezier(.2,.9,.25,1.15) var(--delay) both; }}
/* The capsule centres itself inside a flex item, which shoved the result
   block off-axis; pin its box so icon and label sit together. */
.result .capsule {{ margin:0; flex:0 0 auto; }}
.resultlabel {{ font-family:"{t.font_head}", sans-serif; font-size:40px; color:{t.accent_hot}; }}

/* T7 SCREEN_CARD */
.screencard {{ display:flex; gap:{t.grid}px; }}
.screenrule {{ width:4px; background:{t.accent}; border-radius:2px; }}
.screendomain {{ font-size:26px; color:{t.muted}; }}
.screenhead {{ font-family:"{t.font_head}", sans-serif; font-weight:700; font-size:44px;
  margin:12px 0; }}
.screenhead mark {{ background:rgba(225,29,72,.22); border-radius:6px; color:{t.text};
  padding:0 6px; }}
.screendate {{ font-family:"{t.font_num}", monospace; font-size:26px; color:{t.muted}; }}
.screenlead {{ font-size:30px; color:{t.text}; margin-top:12px; opacity:.85; }}

/* Capsule (§9.4) */
.capsule {{
  width:var(--size); height:var(--size); margin:0 auto;
  border-radius:50%; background:rgba(241,245,249,.06);
  border:1px solid rgba(241,245,249,.14);
  display:flex; align-items:center; justify-content:center; overflow:hidden;
}}
.capsule.danger {{ border-color:{t.accent}; box-shadow:{t.glow_text};
  animation:pulse 1.1s ease-in-out infinite; }}
.capsule img {{ width:64%; height:64%; object-fit:contain; }}
.glyph {{ font-size:calc(var(--size) * .42); color:{t.text}; }}

@keyframes rise {{ from {{ opacity:0; transform:translateY(26px); }} to {{ opacity:1; transform:none; }} }}
@keyframes pop {{ from {{ opacity:0; transform:scale(.86); }} to {{ opacity:1; transform:scale(1); }} }}
@keyframes fade {{ from {{ opacity:0; }} to {{ opacity:1; }} }}
@keyframes grow {{ from {{ width:0; }} to {{ width:var(--w); }} }}
@keyframes draw {{ from {{ transform:scaleX(0); transform-origin:left; }} to {{ transform:scaleX(1); }} }}
@keyframes stroke {{ to {{ stroke-dashoffset:0; }} }}
@keyframes pulse {{ 0%,100% {{ box-shadow:0 0 22px rgba(225,29,72,.35); }}
  50% {{ box-shadow:0 0 46px rgba(225,29,72,.75); }} }}
"""


_PAGE = """<!DOCTYPE html>
<html lang="ru"><head><meta charset="utf-8"><title>{title}</title>
<style>{css}</style></head><body>{body}</body></html>
"""
